# Generated by Django 4.2.4 on 2023-09-01 13:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 1, 13, 22, 3, 533196, tzinfo=datetime.timezone.utc)),
        ),
    ]
